# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Location'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
