# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20190314_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='location',
        ),
    ]
